### ISSUE TITLE
greeting thread

### ISSUE THREAD

**Issue by bravocado** [pimax/fb-messenger-php#14]
Thanks for your effort to build this! :)

I've got this submiting a review for my bot:

```
To help us review your messenger experience, please resubmit with conversation starters and expected responses in the relevant language. Please submit in this format: 
A: Conversation starter (in the relevant language)
B: Expected response from the business 
A: Conversation starter #2 
B: Expected response #2
```

Actually it's just as simple as conversation starter. You can take a look at this: https://developers.facebook.com/docs/messenger-platform/thread-settings

will you build a greeting thread model?

**Comment by chrisplusplus** [comment]
All you have to do is simply make one post request to Facebook in order to set this.  It isn't something that is necessarily part of the user interaction in my opinion. Just open a terminal and make the post request as defined here https://developers.facebook.com/docs/messenger-platform/thread-settings.  One and done.

**Comment by bravocado** [comment]
@chrisplusplus Ah, got it. Thanks for your explanation. :)
